move brewfile's mas apps to brewfile_mas
Because GitHub Actions can't install the mas app.
> Error: Unable to install Blurred app. mas not signed in to Mac App Store.